# -*- coding:utf-8-unix -*-
#+LANGUAGE:  zh
#+TITLE:     纪秀峰_个人简历
#+AUTHOR:    纪秀峰
#+EMAIL:     jixiuf@gmail.com
#+DATE:     2012-03-14 三
#+DESCRIPTION:个人简历
#+KEYWORDS: 个人简历
#+OPTIONS:   H:2 num:nil toc:nil \n:t @:t ::t |:t ^:nil -:t f:t *:t :t
#+TAGS:
#+URI:         /author/
* 基本信息
  |------------+--------------------|
  | 电    话   | 17801090953        |
  | 出生年月   | 1989-01            |
  | E-mail     | jixiuf@qq.com　    |
  | 英语水平   | 六级460            |
  | 毕业院校   | 青岛科技大学       |
  | 学    历   | 本科 2007-9~2011-7 |
  | 户口所在地 | 山东青岛           |
  | 现居住地   | 北京海淀区         |
* 择业目标：
  + Golang 服务端 开发工程师
* 自我介绍：
GitHub个人主页：            https://github.com/jixiuf
个人博客:                 http://jixiuf.github.io/blog/
公司Golang部分开源代码： https://github.com/0studio （90%以上是我提交）
以上几个网址是个人成果的展示，
* 专业技能：
+ 五年多golang 开发经验,简单了解docker、etcd、vitess等开源项目（2014.03~至今）
+ 两年erlang 游戏后端开发经验（2012-3 ~ 2014~3）
+ 熟悉java、为eclipse 写过插件 https://github.com/emacs-java/eclipse_goto_editor
+ 简单了解python,用其做过 游戏管理后台
+ 熟悉linux开发环境，两年Emacs编辑器使用经验，为emacs开源社区贡献过代码，


* 开发经验：
- （2017-8~至今）就职于北京思维造物信息科技有限公司(罗辑思维&得到App)
    负责得到App后端组通用缓存框架的搭建及参与得到App后端业务开发
    为后端组提供通用多级缓存框架，实现缓存快速扩容以应对活动期间流量突增
    提供工具自动生成模块化代码，自动生成数据库的增删改查等方法、及与多级缓存框架的配合，以提高后端开发效率
    提供工具实现将golang 的struct 序列化反序列化成protobuf以提高开发效率
    搭建配置中心及推进后端组各服务接入配置中心、服务注册与发现
    开发并完善后端组web基础框架，使其同时支持HTTP及GRPC
    主要技术框架 Golang+mysql+redis

-	（2016-2~2017-8）就职于北京纳加科技有限公司
    负责后端组的游戏架构与开发工作
    跟几个朋友一起创业，小团队，主要做手机游戏开发。
    主要负责服务端架构设计及代码编写，采用的架构基本继承上个公司所设计的那一套
     主要技术框架 golang+mysql+etcd+memcached+redis。
    因创业失败而团队解散离职
-	 (2013-8~2016-2)就职于北京雪狸科技有限公司
    前期一人负责游戏后端的架构设计与代码编写，采用Golang作为后端语言
    两年内开发了两款手游超神传奇与casino街机电玩大师
    等几款游戏的服务端开发。最初后端只我一人。
    基本架构由我设计,主要语言 golang， 数据存储选用mysql 为应对高并发根据玩家ID进行了mysql分库设计。
    golang 前期GC较差 故用memcache 作缓存，以减少go游戏进程的内存消耗,减少GC卡顿。
    排行榜相关使用redis存储,及玩家操作、流水数据转化成sql语句 push 到redis队列中，供以后pop到mysql 做后期数据统计与分析。
    使用了etcd 来做服务发现及负载均衡,游戏进程启动时会将自身信息注册到etcd中，
    玩家认证用的进程，会监听etcd的变化，并根据其中各游戏进程的负载信息来将玩家平分到游戏进程上。
    即可以根据玩家数量调整服务器进程数量，使游戏进程水平可扩展。


-  (2011-7~2013-8)网页游戏乱世诛魔及兰陵王 就职于北京纯白科技(Erlang)
   参与网页游戏乱世诛魔及兰陵王的开发
   主要使用的技术 erlang+mysql
   乱世诛魔游戏在腾讯游戏平台当时开服700多个。 在乱世诛魔项目中主要参与游戏服务端代码的编写，实现策划设计的新功能。
   优化改造了此项目中读取策划文档数据的方式，加快了服务端程序的启动速度。
   之后转到新项目组兰陵王,在乱世诛魔项目代码基础上进行开发。
   对代码进行了较大改造 ，数据存储由原来的mnesia改成mysql,编写了底层连接mysql 数据库相关的代码，
   并对大量游戏基础模块的数据存储进行改造。
   改造完成之后兰陵王 项目正式立项， 与其他成员一些完成新的游戏逻辑的编写

