name: Build and publish to pages
on:
  push:
    branches:
    - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: docker://iquiw/alpine-emacs
      if: github.event.deleted == false
      with:
        args: sh -c "apk add git;git checkout master;git checkout source;emacs -nw  -q -l ./build/org-publish.el --batch --funcall toggle-debug-on-error  --funcall publish-my-note-all"
    - name: deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./
