name: Build and publish to pages
on:
  push:
    branches:
    - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        ref: 'source'
    - name: build
      uses: docker://iquiw/alpine-emacs
      if: github.event.deleted == false
      with:
        args: emacs -nw  -q -l ./build/org-publish.el --batch --funcall toggle-debug-on-error  --eval "(publish-my-note-all)" --eval '(with-current-buffer "*Messages*"(shell-command-on-region (point-min)(point-max) "cat >/tmp/emacs-org-page.log"))'
    - name: deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./
